# Generated by Django 3.2.18 on 2023-05-01 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230501_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public_id',
            field=models.CharField(default='f3fea2808d604c97a571e8c1e47ce616', max_length=40),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 1, 13, 3, 35, 672725, tzinfo=utc), verbose_name='date of publish'),
        ),
    ]
